spring:
  application:
    name: api-gateway

server:
  port: 8760

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon-hystrix
    api-b:
      path: /api-b/**
      serviceId: service-feign-hystrix