spring:
  application:
      name: config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/dickenschen/springclouddemo
            searchPaths: config
        label: master
server:
  port: 8750

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
