spring:
  application:
    name: service-feign-hystrix

server:
  port: 8767

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  hystrix:
    enabled: true